name: Deploy featuredeploy
on:
  push:
    branches:
      - deploy-to-production

jobs:
  deploy-production-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
        with:
          ref: deploy-to-production
      
      - name: ls -l
        run: ls -l
      
      - name: Install Heroku Cli
        run: |
          curl https://cli-assets.heroku.com/install-standalone.sh | sh

      - name: Install Heroku SSH public key
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "|1|JM96L3t7dJ6cpii5CaQIRiMm2Wc=|8Zw3VhpDXNTR0fHNOujUm40Pxbk= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==" >> ~/.ssh/known_hosts
      - name: Install Heroku netrc credentials
        run: |
          touch ~/.netrc
          echo $HEROKU_NETRC >> ~/.netrc
        env:
          HEROKU_NETRC: ${{ secrets.HEROKU_NETRC }}

      - name: ls -l
        run: ls -l

      - name: Deploy to Heroku
        run: |
          git push https://git.heroku.com/featuredeploy.git `git rev-parse --short HEAD`:refs/heads/master -f
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: ls -l
        run: ls -l
  
